//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vocaber1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[{\"lang_name\":\"английский\",\"lang_code\":\"en\"},\r\n{\"lang_name\":\"русский\",\"lang_code\"" +
            ":\"ru\"},\r\n{\"lang_name\":\"азербайджанский\",\"lang_code\":\"az\"},\r\n{\"lang_name\":\"малаял" +
            "ам\",\"lang_code\":\"ml\"},\r\n{\"lang_name\":\"албанский\",\"lang_code\":\"sq\"},\r\n{\"lang_name" +
            "\":\"мальтийский\",\"lang_code\":\"mt\"},\r\n{\"lang_name\":\"амхарский\",\"lang_code\":\"am\"},\r" +
            "\n{\"lang_name\":\"македонский\",\"lang_code\":\"mk\"},\r\n{\"lang_name\":\"маори\",\"lang_code\"" +
            ":\"mi\"},\r\n{\"lang_name\":\"арабский\",\"lang_code\":\"ar\"},\r\n{\"lang_name\":\"маратхи\",\"lan" +
            "g_code\":\"mr\"},\r\n{\"lang_name\":\"армянский\",\"lang_code\":\"hy\"},\r\n{\"lang_name\":\"марий" +
            "ский\",\"lang_code\":\"mhr\"},\r\n{\"lang_name\":\"африкаанс\",\"lang_code\":\"af\"},\r\n{\"lang_n" +
            "ame\":\"монгольский\",\"lang_code\":\"mn\"},\r\n{\"lang_name\":\"баскский\",\"lang_code\":\"eu\"}" +
            ",\r\n{\"lang_name\":\"немецкий\",\"lang_code\":\"de\"},\r\n{\"lang_name\":\"башкирский\",\"lang_c" +
            "ode\":\"ba\"},\r\n{\"lang_name\":\"непальский\",\"lang_code\":\"ne\"},\r\n{\"lang_name\":\"белорус" +
            "ский\",\"lang_code\":\"be\"},\r\n{\"lang_name\":\"норвежский\",\"lang_code\":\"no\"},\r\n{\"lang_n" +
            "ame\":\"бенгальский\",\"lang_code\":\"bn\"},\r\n{\"lang_name\":\"панджаби\",\"lang_code\":\"pa\"}" +
            ",\r\n{\"lang_name\":\"бирманский\",\"lang_code\":\"my\"},\r\n{\"lang_name\":\"папьяменто\",\"lang" +
            "_code\":\"pap\"},\r\n{\"lang_name\":\"болгарский\",\"lang_code\":\"bg\"},\r\n{\"lang_name\":\"перс" +
            "идский\",\"lang_code\":\"fa\"},\r\n{\"lang_name\":\"боснийский\",\"lang_code\":\"bs\"},\r\n{\"lang" +
            "_name\":\"польский\",\"lang_code\":\"pl\"},\r\n{\"lang_name\":\"валлийский\",\"lang_code\":\"cy\"" +
            "},\r\n{\"lang_name\":\"португальский\",\"lang_code\":\"pt\"},\r\n{\"lang_name\":\"венгерский\",\"" +
            "lang_code\":\"hu\"},\r\n{\"lang_name\":\"румынский\",\"lang_code\":\"ro\"},\r\n{\"lang_name\":\"вь" +
            "етнамский\",\"lang_code\":\"vi\"},\r\n{\"lang_name\":\"гаитянский(креольский)\",\"lang_code\"" +
            ":\"ht\"},\r\n{\"lang_name\":\"себуанский\",\"lang_code\":\"ceb\"},\r\n{\"lang_name\":\"галисийски" +
            "й\",\"lang_code\":\"gl\"},\r\n{\"lang_name\":\"сербский\",\"lang_code\":\"sr\"},\r\n{\"lang_name\":" +
            "\"голландский\",\"lang_code\":\"nl\"},\r\n{\"lang_name\":\"сингальский\",\"lang_code\":\"si\"},\r" +
            "\n{\"lang_name\":\"горномарийский\",\"lang_code\":\"mrj\"},\r\n{\"lang_name\":\"словацкий\",\"la" +
            "ng_code\":\"sk\"},\r\n{\"lang_name\":\"греческий\",\"lang_code\":\"el\"},\r\n{\"lang_name\":\"слов" +
            "енский\",\"lang_code\":\"sl\"},\r\n{\"lang_name\":\"грузинский\",\"lang_code\":\"ka\"},\r\n{\"lang" +
            "_name\":\"суахили\",\"lang_code\":\"sw\"},\r\n{\"lang_name\":\"гуджарати\",\"lang_code\":\"gu\"}," +
            "\r\n{\"lang_name\":\"сунданский\",\"lang_code\":\"su\"},\r\n{\"lang_name\":\"датский\",\"lang_cod" +
            "e\":\"da\"},\r\n{\"lang_name\":\"таджикский\",\"lang_code\":\"tg\"},\r\n{\"lang_name\":\"иврит\",\"l" +
            "ang_code\":\"he\"},\r\n{\"lang_name\":\"тайский\",\"lang_code\":\"th\"},\r\n{\"lang_name\":\"идиш\"" +
            ",\"lang_code\":\"yi\"},\r\n{\"lang_name\":\"тагальский\",\"lang_code\":\"tl\"},\r\n{\"lang_name\":" +
            "\"индонезийский\",\"lang_code\":\"id\"},\r\n{\"lang_name\":\"тамильский\",\"lang_code\":\"ta\"}," +
            "\r\n{\"lang_name\":\"ирландский\",\"lang_code\":\"ga\"},\r\n{\"lang_name\":\"татарский\",\"lang_c" +
            "ode\":\"tt\"},\r\n{\"lang_name\":\"итальянский\",\"lang_code\":\"it\"},\r\n{\"lang_name\":\"телугу" +
            "\",\"lang_code\":\"te\"},\r\n{\"lang_name\":\"исландский\",\"lang_code\":\"is\"},\r\n{\"lang_name\"" +
            ":\"турецкий\",\"lang_code\":\"tr\"},\r\n{\"lang_name\":\"испанский\",\"lang_code\":\"es\"},\r\n{\"l" +
            "ang_name\":\"удмуртский\",\"lang_code\":\"udm\"},\r\n{\"lang_name\":\"казахский\",\"lang_code\"" +
            ":\"kk\"},\r\n{\"lang_name\":\"узбекский\",\"lang_code\":\"uz\"},\r\n{\"lang_name\":\"каннада\",\"la" +
            "ng_code\":\"kn\"},\r\n{\"lang_name\":\"украинский\",\"lang_code\":\"uk\"},\r\n{\"lang_name\":\"кат" +
            "аланский\",\"lang_code\":\"ca\"},\r\n{\"lang_name\":\"урду\",\"lang_code\":\"ur\"},\r\n{\"lang_nam" +
            "e\":\"киргизский\",\"lang_code\":\"ky\"},\r\n{\"lang_name\":\"финский\",\"lang_code\":\"fi\"},\r\n{" +
            "\"lang_name\":\"китайский\",\"lang_code\":\"zh\"},\r\n{\"lang_name\":\"французский\",\"lang_cod" +
            "e\":\"fr\"},\r\n{\"lang_name\":\"корейский\",\"lang_code\":\"ko\"},\r\n{\"lang_name\":\"хинди\",\"la" +
            "ng_code\":\"hi\"},\r\n{\"lang_name\":\"коса\",\"lang_code\":\"xh\"},\r\n{\"lang_name\":\"хорватски" +
            "й\",\"lang_code\":\"hr\"},\r\n{\"lang_name\":\"кхмерский\",\"lang_code\":\"km\"},\r\n{\"lang_name\"" +
            ":\"чешский\",\"lang_code\":\"cs\"},\r\n{\"lang_name\":\"лаосский\",\"lang_code\":\"lo\"},\r\n{\"lan" +
            "g_name\":\"шведский\",\"lang_code\":\"sv\"},\r\n{\"lang_name\":\"латынь\",\"lang_code\":\"la\"},\r" +
            "\n{\"lang_name\":\"шотландский\",\"lang_code\":\"gd\"},\r\n{\"lang_name\":\"латышский\",\"lang_c" +
            "ode\":\"lv\"},\r\n{\"lang_name\":\"эстонский\",\"lang_code\":\"et\"},\r\n{\"lang_name\":\"литовски" +
            "й\",\"lang_code\":\"lt\"},\r\n{\"lang_name\":\"эсперанто\",\"lang_code\":\"eo\"},\r\n{\"lang_name\"" +
            ":\"люксембургский\",\"lang_code\":\"lb\"},\r\n{\"lang_name\":\"яванский\",\"lang_code\":\"jv\"}," +
            "\r\n{\"lang_name\":\"малагасийский\",\"lang_code\":\"mg\"},\r\n{\"lang_name\":\"японский\",\"lang" +
            "_code\":\"ja\"},\r\n{\"lang_name\":\"малайский\",\"lang_code\":\"ms\"}]")]
        public string Languages {
            get {
                return ((string)(this["Languages"]));
            }
        }
    }
}
